ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    two_d_mode: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
    frequency: 30
    sensor_timeout: 1.0
    odom0: /demo/odom
    imu0: /demo/imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom0_config: [true,  true,  false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_differential: false
    odom0_differential: true
    imu0_queue_size: 10
    odom0_queue_size: 10
